import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Suspense } from "react";
import ResponsiveAppBar from "./NavBar";
import "./globals.css";
import LoadingPage from "./loading";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Bolão",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<ResponsiveAppBar />
				<Suspense fallback={<LoadingPage />}>{children}</Suspense>
			</body>
		</html>
	);
}
